[package]
name = "most_frequent_prime_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
leetcode_lib = { path = "../lib" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "most_frequent_prime_benchmark"
harness = false 